### ISSUE TITLE
facebook acces code wil fail 

### ISSUE THREAD

**Issue by ghost** [facebookarchive/php-graph-sdk#1023]
facebook acces code wil fail 

a try to login when a redirect to the callback page i get the following error 

Graph returned an error: لا يمكن تحميل عنوان URL: لم يتم تضمين نطاق عنوان URL هذا في نطاقات التطبيق. للتمكن من تحميل عنوان URL هذا، يرجى إضافة كل النطاقات والنطاقات الفرعية لتطبيقك إلى الحقل "نطاقات التطبيق" في إعدادات التطبيق.

Translate :: Graph returned an error: Can not load URL: This URL domain is not included in application domains. To be able to upload this URL, please add all domains and subdomains of your app to the "Application domains" field in your app settings.

what do a rong ??

**Comment by phaizullin** [comment]
@boanneu add your domain to Valid OAuth Redirect URI in Facebook Login Settings tab on developers page of you app

**Comment by ghost** [comment]
@phaizullin 

that is just the point, a did it al ready ;)

`$redirect_url       =   "https://www.boann.eu/login/oauth.php?action=facebook";
$this->loginUrl     = $this->helper->getLoginUrl($redirect_url, ["email"]);
return $this->loginUrl;`

![oahout01](https://user-images.githubusercontent.com/14090802/42269725-36f94bb4-7f7f-11e8-9607-9aac56e9056b.PNG)

**Comment by phaizullin** [comment]
try use https://www.boann.eu/login/oauth.php

**Comment by ghost** [comment]
@phaizullin 

get te same result, a have chance it in the Facebook app and in the code

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)

PS: Thanks @phaizullin for your help!
