### ISSUE TITLE
Can't Load URL: The domain of this URL blocked

### ISSUE THREAD

**Issue by Nemra1** [facebookarchive/php-graph-sdk#1025]
idont know why this happend but all my setting is right and nothing miss
Subdomain: https://app.nemra-1.com
login URL:https://app.nemra-1.com/login-with.php?provider=Facebook
Redirect url : https://app.nemra-1.com/import.php?hauth.done=Facebook
and this is my live link
https://www.facebook.com/v2.8/dialog/oauth?auth_type=rerequest&client_id=810104762515966&state=a352ff8001da96b9c72375b83dce2cfb&response_type=code&sdk=php-sdk-5.4.4&redirect_uri=https%3A%2F%2Fapp.nemra-1.com%2Fimport.php%3Fhauth_done%3DFacebook&scope=email

![1](https://user-images.githubusercontent.com/22897987/42291163-54fceab2-7fca-11e8-93df-beb8e315eb69.png)
![2](https://user-images.githubusercontent.com/22897987/42291166-5866dd5c-7fca-11e8-8c96-94f7aba30b95.png)
![3](https://user-images.githubusercontent.com/22897987/42291169-5b073052-7fca-11e8-880c-9b1617a8453d.png)
any help about that

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
