### ISSUE TITLE
cann't install using composer 

### ISSUE THREAD

**Issue by manhag** [facebookarchive/php-graph-sdk#1037]
it gave me that msg
  composer require facebook/graph-sdk
                                                
  [Seld\JsonLint\ParsingException]               
  "./composer.json" does not contain valid JSON  
  Parse error on line 4:                         
  ...-master"    }    {        "require":        
  -------------------^                           
  Expected one of: 'EOF', '}', ',', ']'          
![image](https://user-images.githubusercontent.com/5571625/43674447-568343fa-97d4-11e8-9590-b5fc0e9c3c95.png)

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
