### ISSUE TITLE
"You are calling a deprecated version of the Ads API" when using Graph 2.12

### ISSUE THREAD

**Issue by jdknopp** [facebookarchive/php-graph-sdk#1038]
1. Why would a social login function using the Graph SDK trigger a complaint about the Ads API?
2. 2.12 is supposed to work until May 2020 so why am I already getting an uncaught exception?

This has been happening for years, with every version expiring well before the published date. Doubly annoying since nothing actually changes for our use case. Just updating the default version fixes the issue. Why should I have to deal with the social login function regularly going down when nothing is actually broken? Even changing from v2.X to v3.X didn't require updating anything beyond the version string.

**Comment by LartTyler** [comment]
We just had this happen suddenly to us as well. It would be one thing if the version we were on was actually scheduled to be disabled, but we were on 2.12, and received no notifications that the Graph API would stop working for us. What's the point in indicating that 2.12 will be available until May 2020 if the SDK can suddenly decide to fail without any warning long before that date?

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
