### ISSUE TITLE
Unable to get email

### ISSUE THREAD

**Issue by cristiangheorghe10** [facebookarchive/php-graph-sdk#1043]
Hy, from 3 weeks I cant get the email from the request of PHP SDK. I made a ticket to facebook platfomr but they get me this link.
The request is here: http://prntscr.com/kif2st
the response is here: https://prnt.sc/kicci4
As you see, the email is missing.
When I tested in the facebook test page: email appears https://prnt.sc/kicbwx
Thank you

**Comment by codem360** [comment]
Facebook update all Apis, I think you javascript api for login. There is scope define problom please Use facebook javascript login api like this.
FB.login(function(response) { 
//Your code.
},{scope: 'user_gender,email',return_scopes: true});

**Comment by cristiangheorghe10** [comment]
No, I put the return scopes in the code, and is the same problem.
Thanks

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
