### ISSUE TITLE
Get group likes using graph-api

### ISSUE THREAD

**Issue by gasparyanyur** [facebookarchive/php-graph-sdk#1055]
Hi all . I am trying to get mu gruop liked users, but as a response I am getting incomprehensible data.

So for first I have created the app in my **developers.facebook.com**, and in my app installed this package. 

For example I have took the public club named **kikilos13**. 

So , now I  am getting to take all users which have liked this group.

```
$provider = new Facebook($app_Id,$app_secret,$version);

$data = $provider->request('GET','kikilos13/likes');
```
Now, as a response I am getting data with `appid`, `endpoint `and etc.

Please help me to get working my Facebook-Graph api.. or let me know if i need to reconfigure my app

Thanks!

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
