### ISSUE TITLE
Facebook not showing the featured Image For an Article in my Wordpress Website

### ISSUE THREAD

**Issue by leimeister** [facebookarchive/php-graph-sdk#1060]
When I share an article from my website, the featured preview image showing in post is not the featured image I set for the article. It just use the image placed in the post editor instead.

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)
