### ISSUE TITLE
How to get allow page list from user account

### ISSUE THREAD

**Issue by kevalips** [facebookarchive/php-graph-sdk#1061]
I have a manage_page permission and also I used PHP SDK 3.1

Start with user need to authorize then after asking for manage page in that section I have only two-page steel they display tag **See all pages** which is not correct.

Second thing when choosing only one page for a particular application then. How we get that list of a page which user actually allow for that application.

I try to get list of pages using below screenshot. If I am wrong please correct me.
http://nimb.ws/ns5S1t

**So my final Question is that how can I get only those page which is user is selected for my application?**

For your more information I attach one video link please check that and reply back ASAP
https://www.useloom.com/share/370c24b8f1db4778a8a4f4bf23992c17

**Comment by yguedidi** [comment]
Thank you for posting your issue here!
But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
So I'm closing this, and hope to see you soon contributing to the SDK. :)

**Comment by kevalips** [comment]
> Thank you for posting your issue here!
> But this repository is about the Graph API PHP SDK and reported issues must be related to it, like SDK code bugs, documentation mistakes or new feature suggestions.
> For issues with Graph API itself, you can report a bug in the [Facebook issue tracker](https://developers.facebook.com/bugs/).
> For help about how to use the SDK, [StackOverflow](https://stackoverflow.com) is a better place to get answers. Don't forget to tag your question with the [facebook-php-sdk](https://stackoverflow.com/questions/tagged/facebook-php-sdk) tag.
> So I'm closing this, and hope to see you soon contributing to the SDK. :)

I am also using **Facebook SDK** here is **sample code** which I use for fetch pages for the user. 
http://nimb.ws/sApt9X
