### ISSUE TITLE
storeState function use native PHP session if I don't? 

### ISSUE THREAD

**Issue by fenos** [facebookarchive/php-graph-sdk#39]
Hi, I would like implement the new API on my laravel 4 project. I've been stuck when I tried to get the url login for authenticate the users. Laravel 4 doesn't use native 
sessions to store the values but instead `FacebookRedirectLoginHelper` on the method `storeState` check about if there is any PHP session active other ways throw an exception.

```
if (session_status() !== PHP_SESSION_ACTIVE) {
      throw new FacebookSDKException(
        'Session not active, could not store state.'
      );
    }
```

at this point Obviously i get an exception about that. There is any work around for this?

**Comment by robertlagrant** [comment]
@SammyK when you say `FacebookRedirectLoginHelper` is the only method that handles sessions, what about when you do `FacebookSession::setDefaultApplication('YOUR_APP_ID', 'YOUR_APP_SECRET');` before you call the helper?

**Comment by SammyK** [comment]
@robertlagrant `FacebookSession` has nothing to do with native PHP sessions. That's why it got killed in v4.1 since it's a confusing name.

The method `FacebookSession::setDefaultApplication('YOUR_APP_ID', 'YOUR_APP_SECRET');` only sets static variables and never tries to store anything into persistent storage (like a PHP session).

Hope that helps! :)
